### ISSUE TITLE
Citroen C3 | Steering wheel controls not working

### ISSUE THREAD

**Issue by Limpperi** [Snirpo/aawireless-issues#45] opened 2021-03-20 08:59 UTC
Steering wheel controls doesnt respond to anything at all.
MTP mode is not working with my hu, but direct is. Passthrough is disabled.

Car: Citroen C3 2020 (2017-2020)
Hu: OEM Bosch RCC 
Phone: Oneplus 7 pro running android 11

**Comment by borconi** [comment] 2021-03-20 09:00
Does the problem persists with passthrough enabled as well?

**Comment by Limpperi** [comment] 2021-03-20 09:01
Yes it does

**Comment by AndersWinther-Dahl** [comment] 2021-03-20 09:35
Duplicate of #37?

**Comment by Limpperi** [comment] 2021-03-20 09:38
Actually yes, i think that the 208 uses the same rcc headunit.

**Comment by Snirpo** [comment] 2021-03-20 10:32
Yes issues seem to be related, I'll close this issue.

**Closed by Snirpo** 2021-03-20 10:32 UTC
