### ISSUE TITLE
Peugeot 208 (new new version from 2020)

### ISSUE THREAD

**Issue by borconi** [Snirpo/aawireless-issues#37] opened 2021-03-16 17:53 UTC
My setup:
Car: Peugeot 208 (new new version from 2020)
Phone: Xiamomi MI 10, MIUI 12.0.1

This images looks something like my car:
https://at-media.peugeot.com/sites/default/files/styles/cropping_image/public/field/image/32/PEUGEOT_208_TESTDRIVE_0919TC-149.jpg?itok=OWeA3-NI
Settings: Direct, Passtrough enabled. (This is the only way i can get it to partially work)

The problem in short:
When i first connect after having setup AAwireless it works perfect. BUT When i enter a different menu on my headunit i can (almost) not go back to Android Auto.

Detailed description:
In the car the climatecontrol, FM radio, car settings etc is controlled from the same screen as Android Auto. There is 6 softbuttons on the side of the screen. These are used to switch between Android Auto, Climatecontrol etc. Normal Android Auto works fine without Aawireless.
With Aawireless: When i first connect after having setup AAwireless it works perfect. BUT When i enter a different menu on my headunit i can (almost) not go back to Android Auto. This is because the "Android Auto" softbutton on the side of the headunit is "disabled".
So if i start android auto, go into car climatecontrol - then i can not go back to Android Auto. I know that Android Auto is still running because Spotify is still playing. I can just not get the screen to display it again.

There is a couple of additional problems:
a) The "scrollbutton" on the steeringwheel is not connected to Android Auto. When using Android Auto without Aawireless the input from this is sent to Android Auto (i.e. it can be used to change the track in Spotify). But with Aawireless the scrollwheel just controls the FM radio.
b) The button on the steeringwheel to activate the voicecontrolled Google assistent does not work (this works without Aawireless)

I have found a (bad) workaround:
On the phone select: Settings, Connection & Sharing, Android Auto, Registrer "Hey Google", Activate "Say OK Google" to activate the assistant.
When this is activated i can say "OK GOOGLE", when my car is in the climatecontrol to go back to Android Auto

Finally:
Just to make it clear: I am very happy with the unit, connection time is below 15 sec. Build quality is great. I just hope the above "dealbreaker" can be solved :-)

**Comment by drimulescu** [comment] 2021-03-17 21:30
Hello,
I face the same problems with my Peugeot 2008, 2020 model.
BTW: The photo you've attached is with the 10inch screen, made by continental.
The issue is observed with this infotainment: [BOSCH display](https://www.4tuning.ro/images/2020-peugeot-2008-si-e-2008/2020-peugeot-2008-si-e-2008-c5239f337eae0c6191-0-0-0-0-0.jpg) made by BOSCH (**Peugeot 014 | multi | Peugeot | Bosch | RCC | multi | 085C** )

**Comment by AndersWinther-Dahl** [comment] 2021-03-18 17:21
I have the same problem with my Citroën C4 Grand SpaceTourer 2019.

Recorded a video of it
https://www.icloud.com/photos/#0l9OqP3BksXkapco9_6AzOlPg

I have to use USB direct mode, otherwise AAWirrless boots.
I'm facing the same problem both with and without pass through.

**Comment by AndersWinther-Dahl** [comment] 2021-03-18 21:10
Another observation, the mic-button on the steering wheel doesn't work. Used to start Google Assistant.

**Comment by Limpperi** [comment] 2021-03-18 22:55
Citroen c3 2020

None of the steering buttons work (assistant or changing track)  but soft buttons works ok navigating between aa and climate control, Bosch rcc.

Also if the aaw connecta before headunit starts up, it never connects to aa. Other psa group cara experiencing the same?

**Comment by AndersWinther-Dahl** [comment] 2021-03-20 10:30
I think this setting in Android Auto > Developer settings kind of makes it better
![Screenshot_20210320-112658](https://user-images.githubusercontent.com/10073411/111866678-68f20a00-896f-11eb-8914-1ccc32a4f409.jpg)
I think it's "Request video focus on startup" in English

**Comment by Limpperi** [comment] 2021-03-20 10:36
I have it enabled, otherwise i cant get video to show at all without plugging/unplugging or changing usb mode back to back

**Comment by drimulescu** [comment] 2021-03-20 20:54
Hello @Limpperi 
The phone button from your steering wheel (right side) doesn't work?

**Comment by Limpperi** [comment] 2021-03-20 21:02
Hi @drimulescu 

That works, because its connected to the car via bluetooth. So the call system never really uses android auto. Android auto can read it as im in a call (so i can use android auto dialer) but the call itself always is made between phone and car headunit directly. 

Basically when i am in a call, i can deattach android auto completely and the call keeps on going, even it was called via android autos dialer.

**Comment by drimulescu** [comment] 2021-03-20 21:05
I got your point @Limpperi 
In my case, when I press the phone button(no phone call) on the steering wheel enters AA, so this is another way for me to enter AA while connected via AA wireless besides "Ok google"

**Comment by Limpperi** [comment] 2021-03-20 21:23
@drimulescu Ohh ok interesting! In my case it opens a headunits own ui dropdown where i can navigate to contacts or recent calls using touch or right scrollwheel. Some differences between peugeot and citroen rcc afterall it seems

**Comment by drimulescu** [comment] 2021-03-20 21:33
@Limpperi It does the same thing for me IF the phone is not connected directly via Bluetooth to the car. So I have 2 devices connected via Bluetooth on my phone(AA Wireless and car head unit)

**Comment by Limpperi** [comment] 2021-03-20 23:10
@drimulescu since we have te same units and i dont remember having aaW connected without main bluetooth connection between phone and hu, i can test this tomorrow if i have the same consequences (bluetooth off, forcing aa to take control)

**Comment by tallLeRoy** [comment] 2021-03-20 23:14
Limpperi, with my vehicle a short press on the steering wheel button gets me the head unit voice command. A long press when Android Auto is running with USB or AAWireless gets me to Android Assistant. See if that works in your car too.

**Comment by Limpperi** [comment] 2021-03-20 23:19
@tallLeRoy that tells me that you have integrated nav system in your car. So nac instead of rcc headunit. Im saying this because thats how it works in citroen c3 environment atleast. 

In a nutahell;
Integrated nav (nac): short press -> integrated. Long press - AA
No integrated (rrc): short press -> AA. Long press - Also AA (no phone connected - nothing)

**Comment by AndersWinther-Dahl** [comment] 2021-03-24 18:13
Hi @borconi, 
Is this bug covered in the third group of your update on Indiegogo?

Best regards,
Anders

**Comment by Limpperi** [comment] 2021-04-30 16:58
New finding regarding steering wheel controls:

Normally the controls wont work. But if you first connect AA with a wire, and after that change it to the aawireless, the steering wheel controls work flawlessly untill the next HU reboot.

Wired AA somehow "teaches" the AAW and HU to communicate better

(The video focus error is not fixed with this, so assistant is still the only way to refocus)

**Comment by AndersWinther-Dahl** [comment] 2021-04-30 20:04
> New finding regarding steering wheel controls:
> 
> Normally the controls wont work. But if you first connect AA with a wire, and after that change it to the aawireless, the steering wheel controls work flawlessly untill the next HU reboot.
> 
> Wired AA somehow "teaches" the AAW and HU to communicate better
> 
> (The video focus error is not fixed with this, so assistant is still the only way to refocus)

Sounds like some sort of initial handshake is missing on AAW.

**Comment by Snirpo** [comment] 2021-04-30 20:25
AA communication for USB and WiFi should be exactly the same. Could you try enabling Autofocus in the AAW settings? This functionality is available from app version 1.7.1 and firmware 1.2.0.

**Comment by equi1908** [comment] 2021-05-24 07:51
Same issue here on a 3008 with rcc unit..

**Comment by equi1908** [comment] 2021-05-28 09:35
Also, if you don't like the "hey google" way of getting back to android auto after changing to clima etc through the hw buttons, pushing the steering wheel phone button gets you back to the android auto..

**Comment by borconi** [comment] 2021-06-03 14:47
@drimulescu @Limpperi @AndersWinther-Dahl - could you please give you your exact AAWireless-******* names?

**Comment by Limpperi** [comment] 2021-06-03 16:01
@borconi 

AAWireless-v9FfZQgZ

**Comment by AndersWinther-Dahl** [comment] 2021-06-03 16:46
AAWireless-YFWMY7t7

**Comment by Snirpo** [comment] 2021-06-03 17:48
@AndersWinther-Dahl @Limpperi you should be able to able now. Please make sure the USB mode is on MTP.

**Comment by AndersWinther-Dahl** [comment] 2021-06-03 18:20
@Shirpo and @borconi
Yeah 😎👍
The 1.4 Nissan firmware seems to fix the issues 😁
I'm a very happy man now! Thank you both 👍👍

**Comment by Limpperi** [comment] 2021-06-03 18:27
@Snirpo @borconi 

Everything seems to be working flawlessly now with 1.4 and mtp mode. Really happy about this update! Thank you very much for your work.

**Comment by dosoft** [comment] 2021-06-03 22:46
is 1.4 available for everyone?

**Comment by dosoft** [comment] 2021-06-03 22:50
OnJ7cDWg, plz :) @Snirpo @borconi

**Comment by equi1908** [comment] 2021-06-04 05:31
Please make it also available for me, there are the same problems listed above.

LvVPVnW5

**Comment by Snirpo** [comment] 2021-06-04 05:56
@dosoft @equi1908 You should be able to update now.

**Comment by equi1908** [comment] 2021-06-04 09:59
Updated to 1.4 but nothing seems to change (peugeot 3008, rcc unit). MTP connection doesnt work, MTP forced works but doesnt fix any issues. HW nav button doesnt take me to the android auto screen, only way is using either "ok google" or the steering wheel phone button.

Thank you all for the support!

**Comment by dosoft** [comment] 2021-06-04 10:13
I've updated to the 1.4 and confirm - C5 Aircross + Huawei P30 Pro work in MTP mode. HW buttons (audio, nav, etc) switch everything as expected, next/prev steering wheel buttons also work ok. Thanks!

**Comment by equi1908** [comment] 2021-06-04 10:17
Maybe I should try to hard reset the unit.. Did you change any other settings @dosoft ?

**Comment by dosoft** [comment] 2021-06-04 10:43
> Maybe I should try to hard reset the unit.. Did you change any other settings @dosoft ?

@equi1908 Nope, just MTP. Btw, I still have "Request video focus on startup" enabled in AA dev settings. After the firmware update, I've restarted the head unit to reconnect (in C5A it's just a 'press HW 'audio' button for 10 secs'), and voila!

**Comment by equi1908** [comment] 2021-06-07 07:42
@borconi Are you ok with your Peugeot 208 after the 1.4 update? I am still stuck with the issues I have listed above.. Also I have random restarts of the headunit

**Comment by drimulescu** [comment] 2021-06-07 12:25
@equi1908 
I updated to 1.4 in my 2008, turned on MTP and everything works perfectly, like a wired connection.
Maybe you can try the following: 
Forget all connected cars/clear data/cache for the android auto app and restart the pairing process.
Reset AA wireless.
Reset the head unit to factory settings

**Comment by equi1908** [comment] 2021-06-07 15:42
Tried first the aawireless reset and that was the solution.. Works like a charm!

Thank you guys

**Comment by GUNMANVl** [comment] 2021-06-08 01:36
Peugeot 3008 (2019), the same problems. I will be very grateful to get the 1.4 update!!! 

AAwireless-v0apYyLv

**Comment by GUNMANVl** [comment] 2021-06-09 16:44
Updated to 1.4, nothing changed. Can't connect AAWireless to HU in MTP mode. Tried to reset the AA device, no result.

**Comment by Limpperi** [comment] 2021-06-09 17:28
@GUNMANVl try to wipe cache and data from android auto app, reset aaw again and check that the request video on startup is checked from android auto developer settings. 3008 7" rcc hu should be same as above mentioned

**Comment by equi1908** [comment] 2021-06-09 17:44
@GUNMANVl also check twice that the update was both downloaded and installed. The first time I downloaded the updated but I was never installed it

**Comment by tallLeRoy** [comment] 2021-06-09 17:55
@GUNMANVl  You need to change the USB mode to 'Default' for the special Peugeot mode with firmware 1.4.0 and app 1.9.1

If you had the test firmware, Chiel had substituted the new mode for MTP. The production version kept all of the old modes and named the new mode 'Default'.

LeRoy

**Comment by GUNMANVl** [comment] 2021-06-09 22:05
Cliared the Android Auto cache.  Tried the 'Default' mode, it works excellent!!!  Thank you all for your support and help!!!

**Comment by Snirpo** [comment] 2021-06-10 21:35
I'm closing this issue as it seems to have been fixed in 1.4.0.

**Closed by Snirpo** 2021-06-10 21:35 UTC
